### ISSUE TITLE
Does not work when passed non-ascii via stdin

### ISSUE THREAD

**Issue by ostrolucky** [DaveRandom/amphpWinUtils#2]
function `get_tokens_from_stdin` does not decode utf8 chars passed, so subsequent call in `process_start` using result of this fails

ref: https://github.com/amphp/parallel/issues/40

**Comment by trowski** [comment]
@DaveRandom Would this be as simple as using `CreateProcessW()` instead of `CreateProcess()`?

Edit: After further reading, perhaps the binary needs to be compiled with the unicode option enabled (whatever that means, I'm not really familiar with Windows).

**Comment by ostrolucky** [comment]
@DaveRandom Can you have a look, or mark this library as unmaintained? This is historically the only issue with this library there is, with easy reproducer. Why is no maintainer trying to reproduce it?

**Comment by ostrolucky** [comment]
#3

**Comment by DaveRandom** [comment]
@ostrolucky see #4
